"""Summarise opening-book shadow logs.

Reports PER GAME, not per turn. An opening book is supposed to fire a handful
of times and then go quiet, so a per-turn rate would make a working book look
like a rounding error. The question is what fraction of GAMES it would have
changed, and which decision it changed — the lead is once per game and gates
every step after it.

Usage: book_report.py <book_log.jsonl> [...]
"""
import collections
import json
import sys


def load(paths):
    rows = []
    for p in paths:
        with open(p) as f:
            for line in f:
                line = line.strip()
                if line:
                    rows.append(json.loads(line))
    return rows


def main(paths):
    rows = load(paths)
    if not rows:
        print("no shadow rows — was CB_OPENING_BOOK=shadow set?")
        return 1
    # group by battle_tag: bench lanes append to one log concurrently, so
    # positional grouping would mix games together. Rows without a tag (unit
    # tests, single-game runs) fall back to lead-delimited grouping.
    games = collections.defaultdict(list)
    if any(r.get("battle") for r in rows):
        for r in rows:
            games[r.get("battle")].append(r)
    else:
        for r in rows:
            if r.get("kind") == "lead" or not games:
                games[len(games)].append(r)
            else:
                games[len(games) - 1].append(r)

    n = len(games)
    per_team = collections.Counter()
    changed = 0
    lead_seen = lead_diff = 0
    step_rows = [r for r in rows if r.get("kind") != "lead"]
    agree = sum(1 for r in step_rows if r.get("agree"))
    illegal = sum(1 for r in step_rows if not r.get("legal"))
    margins = [r["margin"] for r in step_rows
               if r.get("margin") is not None and not r.get("agree")]

    for g in games.values():
        per_team[g[0].get("team")] += 1
        diff = False
        for r in g:
            if r.get("kind") == "lead":
                lead_seen += 1
                if not r.get("agree"):
                    lead_diff += 1
                    diff = True
            elif not r.get("agree"):
                diff = True
        if diff:
            changed += 1

    print(f"games with a booked team : {n}")
    print(f"  book would change >=1 decision : {changed}  ({100*changed/max(1,n):.0f}% of games)")
    if lead_seen:
        print(f"  LEAD differs                   : {lead_diff}/{lead_seen}  "
              f"({100*lead_diff/lead_seen:.0f}%)   <- once per game, gates every step")
    print(f"\nstep suggestions (not the lead): {len(step_rows)}"
          f"   = {len(step_rows)/max(1,n):.1f} per game, which is the design")
    if step_rows:
        print(f"  agreed with the search : {agree}  ({100*agree/len(step_rows):.0f}%)"
              "   <- agreement means the book adds nothing here")
        print(f"  book move not even generated by the search : {illegal}")
    if margins:
        margins.sort()
        mid = margins[len(margins) // 2]
        cheap = sum(1 for m in margins if m <= 0.25)
        print(f"\ndisagreements: {len(margins)}   median visit-share margin {mid:.2f}")
        print(f"  within 0.25 (a root prior can flip these): {cheap}"
              f"  ({100*cheap/len(margins):.0f}%)")
        print(f"  above 0.50 (search is convinced; do NOT override): "
              f"{sum(1 for m in margins if m > 0.5)}")
        print("\nVERDICT GUIDE: high agreement -> the search already plays the "
              "line, drop the book.\n  Disagreement at LOW margins -> `weighted` "
              "is the right strength.\n  Disagreement at HIGH margins -> either "
              "the book is wrong or the eval is; read those turns before A/Bing.")
    print("\nper team:")
    for t, c in per_team.most_common():
        print(f"  {t}: {c} games")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1:]))
