"""Summarise opening-book shadow logs.

A BOOK IS A SEQUENCE, AND SHADOW CANNOT OBSERVE ONE. Shadow mode watches the
SEARCH's trajectory, so the moment the lead diverges from the book every later
state is off-policy relative to the line the book describes. Its steps were
written for a game that, in the 2026-08-03 run, only happened 20 times in 200.
Reading a pooled step statistic therefore measures the book applied to games it
never contemplated — which is why this report always splits ON-BOOK from
OFF-BOOK. Measured there: steps fire 3.7/game on-book vs 2.2 off-book, the
search agrees 28% vs 16%, and EVERY step fires earlier on-book (Growth turn 8
vs 19, Trick Room 6 vs 9). Late firing was a symptom of divergence, not a
design flaw, and an earlier reading of the pooled numbers wrongly concluded the
steps needed turn bounds.

The LEAD is exempt from all of this: it is decision #1, nothing precedes it, so
it can never be off-policy. It is the one part of a book shadow can measure
honestly.

Reports PER GAME, not per turn. An opening book is supposed to fire a handful
of times and then go quiet, so a per-turn rate would make a working book look
like a rounding error. The question is what fraction of GAMES it would have
changed, and which decision it changed — the lead is once per game and gates
every step after it.

Usage: book_report.py <book_log.jsonl> [...]
"""
import collections
import json
import sys


def load(paths):
    rows = []
    for p in paths:
        with open(p) as f:
            for line in f:
                line = line.strip()
                if line:
                    rows.append(json.loads(line))
    return rows


def main(paths):
    rows = load(paths)
    if not rows:
        print("no shadow rows — was CB_OPENING_BOOK=shadow set?")
        return 1
    # group by battle_tag: bench lanes append to one log concurrently, so
    # positional grouping would mix games together. Rows without a tag (unit
    # tests, single-game runs) fall back to lead-delimited grouping.
    games = collections.defaultdict(list)
    if any(r.get("battle") for r in rows):
        for r in rows:
            games[r.get("battle")].append(r)
    else:
        for r in rows:
            if r.get("kind") == "lead" or not games:
                games[len(games)].append(r)
            else:
                games[len(games) - 1].append(r)

    n = len(games)
    per_team = collections.Counter()
    changed = 0
    lead_seen = lead_diff = 0
    step_rows = [r for r in rows if r.get("kind") != "lead"]
    agree = sum(1 for r in step_rows if r.get("agree"))
    illegal = sum(1 for r in step_rows if not r.get("legal"))
    margins = [r["margin"] for r in step_rows
               if r.get("margin") is not None and not r.get("agree")]

    for g in games.values():
        per_team[g[0].get("team")] += 1
        diff = False
        for r in g:
            if r.get("kind") == "lead":
                lead_seen += 1
                if not r.get("agree"):
                    lead_diff += 1
                    diff = True
            elif not r.get("agree"):
                diff = True
        if diff:
            changed += 1

    print(f"games with a booked team : {n}")
    print(f"  book would change >=1 decision : {changed}  ({100*changed/max(1,n):.0f}% of games)")
    if lead_seen:
        print(f"  LEAD differs                   : {lead_diff}/{lead_seen}  "
              f"({100*lead_diff/lead_seen:.0f}%)   <- once per game, gates every step")
    print(f"\nstep suggestions (not the lead): {len(step_rows)}"
          f"   = {len(step_rows)/max(1,n):.1f} per game, which is the design")
    if step_rows:
        print(f"  agreed with the search : {agree}  ({100*agree/len(step_rows):.0f}%)"
              "   <- agreement means the book adds nothing here")
        print(f"  book move not even generated by the search : {illegal}")
    if margins:
        margins.sort()
        mid = margins[len(margins) // 2]
        cheap = sum(1 for m in margins if m <= 0.25)
        print(f"\ndisagreements: {len(margins)}   median visit-share margin {mid:.2f}")
        print(f"  within 0.25 (a root prior can flip these): {cheap}"
              f"  ({100*cheap/len(margins):.0f}%)")
        print(f"  above 0.50 (search is convinced; do NOT override): "
              f"{sum(1 for m in margins if m > 0.5)}")
        print("\nVERDICT GUIDE: high agreement -> the search already plays the "
              "line, drop the book.\n  Disagreement at LOW margins -> `weighted` "
              "is the right strength.\n  Disagreement at HIGH margins -> either "
              "the book is wrong or the eval is; read those turns before A/Bing.")
    # on-book vs off-book: the only coherent way to read step rows
    on = off = None
    if lead_seen:
        on_s, off_s, on_g, off_g = [], [], 0, 0
        for g in games.values():
            ld = [r for r in g if r.get("kind") == "lead"]
            if not ld:
                continue
            st = [r for r in g if r.get("kind") != "lead"]
            if ld[0].get("agree"):
                on_g += 1; on_s += st
            else:
                off_g += 1; off_s += st
        print("\nSTEPS SPLIT BY WHETHER THE LINE WAS EVER ENTERED")
        print("  (off-book step rows describe games the book never contemplated)")
        for lab, st, ng in (("on-book ", on_s, on_g), ("off-book", off_s, off_g)):
            if not st:
                continue
            a = sum(1 for r in st if r.get("agree"))
            print(f"  {lab}: {ng:>3} games, {len(st):>4} steps "
                  f"({len(st)/max(1,ng):.1f}/game), agreement {100*a/len(st):.0f}%")
    print("\nper team:")
    for t, c in per_team.most_common():
        print(f"  {t}: {c} games")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1:]))
