#!/usr/bin/env python3
"""Generate showdown/lead_measured.json — our OWN empirical lead quality.

Deliberately SEPARATE from roles.json. roles.json carries the intrinsic,
curated claim (what is true of the mon in OU); this file carries what our
pilot actually achieves. Keeping them apart is what let us localise the
Ting-Lu gap: curated strong + field's most-led mon + costs US 3.3pp = the
engine sets the hazards and fails to convert. A single merged field would
have destroyed that signal.

METHOD — within-matchup matched delta. For each lead species: winrate when
leading it MINUS winrate leading anything else, computed inside a FIXED
(our team, opponent team) cell and averaged over cells. The matching is what
makes it causal-ish: inside one cell the preview pick varies from MCTS
stochasticity alone, which approximates random assignment. Unmatched numbers
overstate badly (Kingambit reads -12.7pp raw vs -8.1pp matched).

The numbers are CONDITIONED on our sets, our teams and the opponent pool —
they are not facts about the species. Regenerate when either changes.

Usage: .venv/bin/python showdown/build_lead_measured.py [glob ...]
"""
import glob as _glob
import json
import math
import re
import sys
from collections import defaultdict

DEFAULT = ["showdown/bench/dittoab3_0806_L*_ours.log",
           "showdown/bench/dittoab0806_L*_ours.log",
           "showdown/bench/dtscreen0806b_L*_ours.log"]
norm = lambda s: re.sub(r"[^a-z0-9]", "", s.lower())


def collect(patterns):
    cell = defaultdict(lambda: defaultdict(lambda: [0, 0]))
    for pat in patterns:
        for f in sorted(_glob.glob(pat)):
            ours = theirs = lead = win = None
            started = False
            def flush():
                if lead and win and ours and theirs:
                    c = cell[(ours, theirs)][lead]
                    c[1] += 1
                    c[0] += win.startswith("CBGen9")
            for line in open(f, errors="replace"):
                m = re.search(r"team: G\d+_([a-z0-9]+)_.*?_vs_(\S+?) \(", line)
                if m:
                    flush()
                    ours, theirs = m.group(1), m.group(2)
                    lead = win = None
                    started = False
                    continue
                if not line.startswith("|"):
                    continue
                p = line.rstrip().split("|")
                k = p[1] if len(p) > 1 else ""
                if k == "turn":
                    started = True
                elif (k == "switch" and len(p) > 3 and p[2][:2] == "p2"
                      and not started and lead is None):
                    lead = norm(p[3].split(",")[0])
                elif k == "win" and len(p) > 2:
                    win = p[2].strip()
            flush()
    return cell


def main():
    pats = sys.argv[1:] or DEFAULT
    cell = collect(pats)
    deltas = defaultdict(list)
    totals = defaultdict(lambda: [0, 0])
    for leads in cell.values():
        n_all = sum(v[1] for v in leads.values())
        for sp, (w, n) in leads.items():
            totals[sp][0] += w
            totals[sp][1] += n
            ow = sum(v[0] for s, v in leads.items() if s != sp)
            on = n_all - n
            if n >= 5 and on >= 5:
                deltas[sp].append(w / n - ow / on)
    out = {}
    for sp, d in deltas.items():
        if len(d) < 8:
            continue
        m = sum(d) / len(d)
        sd = math.sqrt(sum((x - m) ** 2 for x in d) / max(len(d) - 1, 1))
        se = sd / math.sqrt(len(d))
        w, n = totals[sp]
        out[sp] = {"delta_pp": round(100 * m, 1),
                   "ci95_pp": [round(100 * (m - 1.96 * se), 1),
                               round(100 * (m + 1.96 * se), 1)],
                   "games_led": n, "raw_winrate": round(w / n, 3),
                   "matched_cells": len(d)}
    doc = {"_comment": [
        "GENERATED by showdown/build_lead_measured.py — do not hand-edit.",
        "Our pilot's measured lead quality; the intrinsic/curated claim lives",
        "in roles.json as lead_quality. Where the two DISAGREE that is a",
        "pilot-fit gap, not an error in either.",
        "Conditioned on our sets/teams and the opponent pool used.",
        "delta_pp = within-matchup matched winrate delta for leading this mon.",
    ], "sources": pats, "leads": dict(sorted(
        out.items(), key=lambda kv: -kv[1]["delta_pp"]))}
    json.dump(doc, open("showdown/lead_measured.json", "w"), indent=2)
    print(f"wrote {len(out)} species to showdown/lead_measured.json")
    for sp, v in list(doc["leads"].items()):
        print(f"  {sp:20s} {v['delta_pp']:+6.1f}pp  {v['ci95_pp']}  n={v['games_led']}")


if __name__ == "__main__":
    main()
